# x=open("rejo.txt","x")
# x.close()
# y=open("rejo.txt","a")
# print(y.write("hi guys its time to do some work"))
# y.close()
# y=open("rejo.txt","w")
# print(y.write("hello guys its me"))
# y.close()
# y=open("rejo.txt","r")
# y.close()
# z=open("kk.txt","x")
# z.close()
x=open("rejo.txt","r")
m=x.read()
print(m)
y=open("kk.txt","w")
y.write(m)
y.close()
z=open("kk.txt","r")
print(z.read())