# a=open("sf.txt","x")
# a=open("sf.txt","w")
# a.write("iam so cool")
# a.close()
# a=open("sf.txt","a")
# a.write("hello guys iam back")
# a.close()
# a=open("sf.txt","r")
# print(a.read())
# print(a.read(6))
# print(a.readline())
# a.close()
t=open("its me","x")
# # os.remove("its me")