import os
x=open("sample.txt","r")
# print(x.read())
# print(x.read(5))
print(x.readline())
print(x.readline())
x.close()
x=open("sample.txt","a")
x.write("iam gentle")
x.close()
x=open("sample.txt","r")
print(x.read())
x.close()
x=open("sample.txt","w")
x.write("its soo beautiful")
x.close()
x=open("sample.txt","r")
print(x.read())
x.close()
# n=open("sam.txt","x")
# os.remove("sam.txt")
os.rmdir("empty folder")