age=(23,12,2,50,14,16,20,25)
print(age)
print(type(age))
print(len(age))
print(age[1])
colour=("red",)
print(type(colour))
colour=tuple(("red","orange","green","purple","black,"))
print(colour)
print(colour[2])
print(colour[-1])
print(colour[2:4])
print(colour[:3])
print(colour[2:])
print("red" in colour)
print("blue" not in colour)
y=list(colour)
print(y)
y[2]="brown"
print(y)
colour=tuple(y)
print(colour)
for i in colour:
    print(i)
print(colour+age)
r=(20,30,40,50,60,70,80,90,90)
print(r*5)
print(r.count(90))