# x=open("rahul.txt","x")
# x.close()
# y=open("rahul.txt","a")
# print(y.write("hello its time to race"))
# y.close()
# n=open("look.txt","x")
# n.close()
# p=open("look.txt","a")
# print(p.write("iam ready to race"))
# p.close()
# z=open("top.txt","x")
# z.close()
x=open("rahul.txt","r")
m=x.read()
print(m)
p=open("look.txt","r")
n=p.read()
print(n)
z=open("top.txt","w")
z.write(m)
z=open("top.txt","a")
z.write(n)