number=(1,2,3,4,5,6,7,8)
print(number)
print(type(number))
print(len(number))
print(number[1])
colour=("red",)
print(type(colour))
colour=tuple(("red","blue","black","brown","purple"))
print(colour)
print(colour[2:4])
print(colour[-4:-2])
print(colour[-1])
print(colour[:2])
print(colour[3:])
print("red" in colour)
print("rose" not in colour)
y=list(colour)
print(y)
y[1]="green"
print(y)
colour=tuple(y)
print(colour)
for i in colour:
    print(i)
print(colour+number)
x=(2,3,3,4)
print(x*4)
print(x.count(3))